export { default as BarChart } from './BarChart.vue'
export { default as LineChart } from './LineChart.vue'
export { default as PieChart } from './PieChart.vue'
export { default as DoughnutChart } from './DoughnutChart.vue'
export { default as RadarChart } from './RadarChart.vue'